language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

notifications:
  email:
    on_success: never

script:
  # TODO: test-threads=1 temporarily
  - RUST_BACKTRACE=1 cargo test --verbose --all --test-threads=1
  - RUST_BACKTRACE=1 cargo test --verbose --all --no-default-features --test-threads=1
